export const FAMILY_LOGOS: Partial<Record<string, string>> = {
  qwen: "/brands/qwen.svg",
  deepseek: "/brands/deepseek.svg",
  llama: "/brands/llama.svg",
  gemma: "/brands/gemma.svg",
  mistral: "/brands/mistral.svg",
  "gpt-oss": "/brands/gpt-oss.svg",
  whisper: "/brands/gpt-oss.svg",
  "intern-s": "/brands/internlm.webp",
  internlm: "/brands/internlm.webp",
  phi: "/brands/phi.svg",
  nemotron: "/brands/nemotron.svg",
  glm: "/brands/glm.svg",
  minimax: "/brands/minimax.svg",
  mimo: "/brands/mimo.svg",
  kimi: "/brands/kimi.svg",
  inkling: "/brands/thinking-machines.png",
  laguna: "/brands/poolside.webp",
  solar: "/brands/solar.svg",
  k2: "/brands/k2.webp",
  grok: "/brands/grok.svg",
  cosmos3: "/brands/nemotron.svg",
  lyra: "/brands/nemotron.svg",
  "sana-wm": "/brands/nemotron.svg",
  gr00t: "/brands/nemotron.svg",
  parakeet: "/brands/nemotron.svg",
};
